---
#- name: Openwind | Create folder in Python dist-packages
#  file: path="{{ python_dist_packages }}/openwind" state=directory

- name: Openwind | Update/checkout OpenWind
  git: repo=https://github.com/nansencenter/openwind
       dest="{{ dev_sources_dir }}/openwind"
       version="{{ openwind_version }}"
       update=yes

- name: Openwind | Create link from Python dist-packages to openwind
  file: path='{{ python_dist_packages }}/openwind'
        src='{{ dev_sources_dir }}/openwind/openwind'
        state=link
        force=yes

- name: Openwind | Create link from Python dist-packages to init file of nansat_mappers in openwind
  file: path='{{ python_dist_packages }}/nansat_mappers/__init__.py'
        src='{{ dev_sources_dir }}/openwind/nansat_mappers/__init__.py'
        state=link
        force=yes

- name: Openwind | Create link from Python dist-packages to quikscat mapper in openwind
  file: path='{{ python_dist_packages }}/nansat_mappers/mapper_quikscat.py'
        src='{{ dev_sources_dir }}/openwind/nansat_mappers/mapper_quikscat.py'
        state=link
        force=yes

- name: Openwind | Create link from Python dist-packages to openwind_integration_tests
  file: path='{{ python_dist_packages }}/openwind_integration_tests'
        src='{{ dev_sources_dir }}/openwind/openwind_integration_tests'
        state=link
        force=yes

- name: Openwind | Create link from Python dist-packages to openwind_local_archive.py
  file: path='{{ python_dist_packages }}/openwind_local_archive.py'
        src='{{ dev_sources_dir }}/openwind/templates/openwind_local_archive.py'
        state=link
        force=yes

- name: OpenWind Setup Python | Install cartopy
  shell: 'conda install cartopy'

