---
- hosts: course
  roles:
    - localvm
    - conda
    - nansat
    - sample_datasets
    - course
    - geospaas_catalog
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"
    
- hosts: geospaas_core
  roles:
    - localvm
    - conda
    - nansat
    - sample_datasets
    - geospaas_catalog
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"
    CPL_ZIP_ENCODING: "UTF-8"

- hosts: doppler
  roles:
    - localvm
    - conda
    - nansat
    - openwind
    - sample_datasets
    - geospaas_catalog
    - svp_drifters
    - doppler
    #- liclipse
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"

- hosts: doppler_prod
  roles:
    - localvm
    - conda
    - nansat
    - openwind
    - sample_datasets
    - geospaas_catalog
    - svp_drifters
    - doppler
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"

- hosts: metsarvind
  roles:
    - localvm
    - conda
    - nansat
    - openwind
    - sample_datasets
    - geospaas_catalog
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"

- hosts: globcurrent
  roles:
    - localvm
    - conda
    - nansat
    - course
    - sample_datasets
    - geospaas_catalog
    - svp_drifters
    - globcurrent
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"
    CPL_ZIP_ENCODING: "UTF-8"

- hosts: cmems
  roles:
    - localvm
    - conda
    - nansat
    - course
    - geospaas_catalog
    - cmems
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"
    CPL_ZIP_ENCODING: "UTF-8"

- hosts: icedrifters
  roles:
    - localvm
    - conda
    - nansat
    - geospaas_catalog
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"
    CPL_ZIP_ENCODING: "UTF-8"

- hosts: icetype
  roles:
    - localvm
    - conda
    - nansat
    - geospaas_catalog
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"
    CPL_ZIP_ENCODING: "UTF-8"

- hosts: travis
  roles:
    - conda
    - nansat
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"
